### ISSUE TITLE
Add option to change color of background (or skip it)

### ISSUE THREAD

**Issue by vmario89** [Sternenlabor/fabaccess-sticker-generator#3]
Hi @SunboX - we used the Sticker Generator succcessfully at FAbAccess Showcase in ZAM Erlangen during the Vulca Week.

we figured out that the stickers work well, but would be more easily scannable, if the contrast is much higher. It would be helpful to change the background color from grey to white or sth. else :-)

btw. the sticker generator is kind of officially installed as an instance at https://sticker.fab-access.org - linking back to your source <3

**Comment by SunboX** [comment]
Thanks for the feedback! Yes that's a good idea. I will take a look at the default colors, but what also will go along with this is the feature request here: https://github.com/Sternenlabor/fabaccess-sticker-generator/issues/1

**Comment by SunboX** [comment]
Tasks:

1) Add a white background color to the QR-Code for better scan-ability:
<img src="https://github.com/user-attachments/assets/bbb40342-e733-4500-8bb0-9cc3b563bdbf" width="200px" />


2) Implement a settings menu, where individual colors can be changed (see issue #1)

**Comment by SunboX** [comment]
Fixed with latest master

**Comment by vmario89** [comment]
coole Option mit dem Zahnrädchen! :)) ich wollts gerade testen, hab aber folgendes kleines Problem:

![grafik](https://github.com/user-attachments/assets/9d608d9b-f07a-4d1b-bd7c-9127e335dc43)

Ergebnis im PDF ist schwarz; auch im Preview - getestet in Firefox und Chromium - jeweils gleich

**Comment by vmario89** [comment]
warum auch immer klappt es jetzt bei mir auch! ich habs auch bei sticker.fab-access.org aktualisiert :)

vielen Dank André!
